class Producto():
    def __init__(self, producto_id: int, precio: float, nombre, marca):
        self.producto_id = producto_id
        self.precio = precio
        self.nombre = nombre
        self.marca = marca
        
productos = { # Catalogo de productos
    "arroz": Producto(1, 20, "arroz", "juana"),
    "vino francés": Producto(2, 100, "vino francés", "letelier"),
    "pan": Producto(3, 30, "pan", "bimbo"),
    "leche": Producto(4, 45, "leche", "soprole"),
    "queso": Producto(5, 60, "queso", "colun"),
    "azucar": Producto(6, 25, "azucar", "ian"),
    "sal": Producto(7, 35, "sal", "lobos"),
    "aceite": Producto(8, 90, "aceite", "ideal"),
    "cafe": Producto(9, 120, "cafe", "nescafe"),
    "te": Producto(10, 80, "te", "lipton"),

    "mantequilla": Producto(11, 150, "mantequilla", "soprole"),
    "jamon": Producto(12, 200, "jamon", "pf"),
    "pollo": Producto(13, 180, "pollo", "ariztia"),
    "carne": Producto(14, 350, "carne", "angus"),
    "pescado": Producto(15, 220, "pescado", "san jose"),
    "yogurt": Producto(16, 95, "yogurt", "colun"),
    "galletas": Producto(17, 60, "galletas", "oreo"),
    "cereal": Producto(18, 70, "cereal", "nestle"),
    "chocolate": Producto(19, 55, "chocolate", "milka"),
    "fideos": Producto(20, 40, "fideos", "lucchetti"),

    "harina": Producto(21, 110, "harina", "selecta"),
    "mayonesa": Producto(22, 65, "mayonesa", "kraft"),
    "ketchup": Producto(23, 75, "ketchup", "heinz"),
    "mostaza": Producto(24, 85, "mostaza", "heinz"),
    "atun": Producto(25, 95, "atun", "van camps"),
    "salsa tomate": Producto(26, 130, "salsa tomate", "carozzi"),
    "arvejas": Producto(27, 160, "arvejas", "wasil"),
    "lentejas": Producto(28, 140, "lentejas", "banquete"),
    "garbanzos": Producto(29, 155, "garbanzos", "banquete"),
    "porotos": Producto(30, 210, "porotos", "banquete"),

    "bebida cola": Producto(31, 90, "bebida cola", "coca cola"),
    "bebida naranja": Producto(32, 85, "bebida naranja", "fanta"),
    "bebida limon": Producto(33, 88, "bebida limon", "sprite"),
    "jugo": Producto(34, 120, "jugo", "andina"),
    "agua": Producto(35, 70, "agua", "benedictino"),
    "cerveza": Producto(36, 95, "cerveza", "sol"),
    "cerveza negra": Producto(37, 110, "cerveza negra", "cusquena"),
    "whisky": Producto(38, 500, "whisky", "jack daniels"),
    "ron": Producto(39, 450, "ron", "bacardi"),
    "vodka": Producto(40, 380, "vodka", "absolut"),

    "helado": Producto(41, 60, "helado", "savory"),
    "postre": Producto(42, 75, "postre", "danone"),
    "gelatina": Producto(43, 55, "gelatina", "royal"),
    "pan molde": Producto(44, 95, "pan molde", "ideal"),
    "pan integral": Producto(45, 130, "pan integral", "ideal"),
    "huevos": Producto(46, 200, "huevos", "super pollo"),
    "tocino": Producto(47, 160, "tocino", "pf"),
    "salchichas": Producto(48, 140, "salchichas", "pf"),
    "hamburguesas": Producto(49, 170, "hamburguesas", "notco"),
    "empanadas": Producto(50, 155, "empanadas", "don pedro"),

    "detergente": Producto(51, 65, "detergente", "omo"),
    "suavizante": Producto(52, 85, "suavizante", "downy"),
    "esponja": Producto(53, 45, "esponja", "virutex"),
    "lavaloza": Producto(54, 70, "lavaloza", "quix"),
    "cloro": Producto(55, 95, "cloro", "clorox"),
    "limpiapiso": Producto(56, 110, "limpiapiso", "poett"),
    "desinfectante": Producto(57, 125, "desinfectante", "lysol"),
    "papel higienico": Producto(58, 60, "papel higienico", "elite"),
    "toalla papel": Producto(59, 150, "toalla papel", "nova"),
    "servilletas": Producto(60, 90, "servilletas", "scott"),

    "shampoo": Producto(61, 55, "shampoo", "head shoulders"),
    "acondicionador": Producto(62, 60, "acondicionador", "pantene"),
    "jabon": Producto(63, 45, "jabon", "dove"),
    "pasta dental": Producto(64, 50, "pasta dental", "colgate"),
    "cepillo dientes": Producto(65, 70, "cepillo dientes", "oral b"),
    "desodorante": Producto(66, 85, "desodorante", "axe"),
    "crema corporal": Producto(67, 95, "crema corporal", "nivea"),
    "bloqueador solar": Producto(68, 110, "bloqueador solar", "banana boat"),
    "alcohol gel": Producto(69, 75, "alcohol gel", "simond"),
    "algodon": Producto(70, 65, "algodon", "cotton"),
}